name: Lint terraform manifests
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.9

      - name: Install linter
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.34.0

      - name: Runs linter
        run: |
          ROOT_DIR=$(git rev-parse --show-toplevel);
          DIRECTORIES=$(find . -name '*.tf' | awk -F'/[^/]*$' '{print $1}' | sort | uniq);
          for d in $DIRECTORIES
          do
            echo "Linting $d"
            cd $d
            terraform get >> /dev/null 2>&1
            tflint --config $ROOT_DIR/.tflint.hcl
            cd $ROOT_DIR
          done