name: Validate terraform manifests
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.9

      - name: Initialize terraform
        run: terraform init

      - name: Validate
        run: terraform validate -no-color